name 'chef-aws-storage-gateway-kvm-rhel9'
maintainer 'Erin L. Kolp'
maintainer_email 'erinlkolpfoss@gmail.com'
license 'MIT'
description 'Installs/Configures chef-aws-storage-gateway-kvm-rhel9'
long_description 'Installs/Configures chef-aws-storage-gateway-kvm-rhel9'
version '2025.2.0'
chef_version '>= 14.0'
issues_url 'https://github.com/erinlkolp/chef-aws-storage-gateway-kvm-rhel9/issues'
source_url 'https://github.com/erinlkolp/chef-aws-storage-gateway-kvm-rhel9'
